set_param('StateMachine_test/Right Trigger', 'Value', '0')
set_param('StateMachine_test/Right Safety', 'Value', '0')
set_param('StateMachine_test/Right Scroll Click', 'Value', '0')
set_param('StateMachine_test/Right Scroll Mode', 'Value', '1')
set_param('StateMachine_test/Left Trigger', 'Value', '0')
set_param('StateMachine_test/Left Safety', 'Value', '0')
set_param('StateMachine_test/Both Triggers', 'Value', '0')
set_param('StateMachine_test/Both Safety', 'Value', '0')
